version: '3.1'

services:
  db:
    container_name: timescale
    image: timescale/timescaledb:latest-pg11
    volumes:
      - "./data/db:/var/lib/postgresql/data"
      - "./data/conn:/var/run/postgresql"
    ports:
      - 5432:5432
    expose:
      - 5432
    environment:
      POSTGRES_PASSWORD: starcraft
      POSTGRES_USER: starcraft
      POSTGRES_DB: denos
      PGDATA: /var/lib/postgresql/data

  api:
    container_name: btc_listings_dev
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: go run main.go
    volumes:
      - ./src:/go/src/app
    working_dir: /go/src/app
    ports:
      - "3001:3001"
    environment:
      PORT: 3001
      HOST: 127.0.0.1