version: '3.1'

services:
  db:
    name: timescale
    image: timescale/timescaledb:latest-pg11
    restart: always
    volumes:
      - "./data/db:/var/lib/postgresql/data"
      - "./data/conn:/var/run/postgres"
    ports:
      - 5432:5432
    expose:
      - 5432
    environment:
      POSTGRES_PASSWORD: starcraft
      POSTGRES_USER: starcraft
      POSTGRES_DB: denos
      PGDATA: /var/lib/postgresql/data