version: '3.1'

services:
  db:
    container_name: timescale
    image: timescale/timescaledb:latest-pg11
    volumes:
      - "./data/conn:/var/run/postgresql"
      - "./data/db:/var/lib/postgresql/data"
      - "./migrations:/docker-entrypoint-initdb.d"
    ports:
      - 5432:5432
    expose:
      - 5432
    environment:
      POSTGRES_USER: starcraft
      POSTGRES_PASSWORD: starcraft
      POSTGRES_DB: btc_listings
      PGDATA: /var/lib/postgresql/data

